version: "3.8"

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: worpress_debian
    volumes:
      - wordpress:/var/www/
    networks:
      - localhost
    depends_on:
      - mariadb
    restart: always

  nginx:
      build: ./requirements/nginx
      container_name: nginx_debian
      ports:
        -  "443:443"
      volumes:
        - wordpress:/var/www/
      depends_on:
        - wordpress 
      networks:
        - localhost
      restart: always

  mariadb:
      build: ./requirements/mariadb
      container_name: mariadb_debian
      volumes:
            - mariadb:/var/lib/mysql
      networks:
        - localhost
      restart: always
networks:
  localhost:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
            device: /home/arastepa/data/wordpress
            o: bind
            type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
            device: /home/arastepa/data/mariadb
            o: bind
            type: none

