version: "3.8"

services:
  wordpress:
    build: ./requirements/wordpress
    container_name: wordpress_debian
    volumes:
      - wordpress:/var/www/
    networks:
      - localhost
    env_file:
      - .env
    depends_on:
      - mariadb
    restart: always

  nginx:
      build: ./requirements/nginx
      container_name: nginx_debian
      ports:
        -  "443:443"
      volumes:
        - wordpress:/var/www/
      depends_on:
        - wordpress 
      networks:
        - localhost
      env_file:
        - .env
      restart: always

  mariadb:
      build:
          context: ./requirements/mariadb
          args:
             - MYSQL_DATABASE=${MYSQL_DATABASE}
             - MYSQL_USER=${MYSQL_USER}
             - MYSQL_PASSWORD=${MYSQL_PASSWORD}
             - MYSQL_SUPER_USER=${MYSQL_SUPER_USER}
             - MYSQL_SUPER_PASSWORD=${MYSQL_SUPER_PASSWORD}
      container_name: mariadb_debian
      volumes:
            - mariadb:/var/lib/mysql
      networks:
        - localhost
      restart: always
networks:
  localhost:

volumes:
  wordpress:
    name: wordpress
    driver: local
    driver_opts:
            device: $HOME/data/wordpress
            o: bind
            type: none
  mariadb:
    name: mariadb
    driver: local
    driver_opts:
            device: $HOME/data/mariadb
            o: bind
            type: none

